apiVersion: v1
kind: Pod
metadata:
  name: beemesh-machine
spec:
  restartPolicy: Always
  containers:
    - name: machine
      image: beemesh-machine:latest
      env:
        - name: BEEMESH_PODMAN_SOCKET
          value: /run/podman/podman.sock
      volumeMounts:
        - name: podman-socket
          mountPath: /run/podman/podman.sock
  volumes:
    - name: podman-socket
      hostPath:
        path: /run/podman/podman.sock
        type: Socket